### ISSUE TITLE
can not be opened because an unexpected error occured

### ISSUE THREAD

**Issue by lukecyca** [cy384/ssheven#14] opened 2021-12-09 05:49 UTC
## System details

Power Macintosh 7300
96MB of RAM
System 7.5.5
Open Transport 1.1.1

## Issue

Launching SSHEVEN-FAT produces the following error and immediately quits.

> The application "SSHEVEN-FAT" can not be opened because an unexpected error occured.

**Comment by cy384** [comment] 2021-12-09 14:08
thanks for the report, does it give an error code or any other information?

**Comment by lukecyca** [comment] 2021-12-09 17:53
That's the exact text in the dialog box. No error codes or anything. What's curious is that "occured" is misspelled, but that seems to be the case for [many error messages](https://www.google.com/search?q=%22occured%22+macintosh+system+7.5.5) generated by this era of Mac.

I'm not really sure how to troubleshoot this other than start turning off extensions. Any other advice?

**Comment by cy384** [comment] 2021-12-11 16:35
honestly, no, I haven't done any serious debugging on the mac side of things.  Any chance there was an issue with downloading/transferring/extracting it, and either the resource fork or the data fork got messed up?  Maybe running [this version](http://www.cy384.com/media/bin/ssheven/ssheven-test-68k-only.bin) could make it do something different.

**Comment by lukecyca** [comment] 2021-12-12 07:55
Today I built my RaSCSI kit so I have more options to get stuff on and off of this old machine. I tried `ssheven-0.8.8-fat.bin` and `ssheven-0.8.8-fat.dsk` and both exhibited the same error unfortunately.

I'll try the 68k-only version next, and then start trying with other bootable images with various OS versions.

**Comment by lukecyca** [comment] 2021-12-13 04:52
The 68k-only version seems to work!

I also tried booting from various other clean 7.5.x boot volumes and got the same behaviour each time: the fat version resulted in the same error, but the 68k version worked.

**Comment by cy384** [comment] 2021-12-13 14:01
that's good info, I'll look into the PPC build to see what's going on

**Comment by cy384** [comment] 2021-12-28 04:02
After taking a look on my PPC test machine, ssheven runs fine on 9.1 but not on 8.0.  I'll admit this is the first time I've ever tested, I guess very few people run 7 or early versions of 8 on their PPC machines!  The reported error is:

`The application "ssheven-0.8.8" could not be opened because "InterfaceLib--PBXGetVOlInfoSync" could not be found`

This may be a case where later versions of the OS gave more info in the error message, or it may be a separate problem.  This particular error is apparently caused by using a function which is not available on PPC 8.0 or 8.1.  I'll hack it out for a quick test build tomorrow and see if it runs.

**Comment by cy384** [comment] 2021-12-28 16:11
@lukecyca can you try this version? [http://www.cy384.com/media/bin/ssheven-no-PBXGetVolInfoSync.bin](http://www.cy384.com/media/bin/ssheven-no-PBXGetVolInfoSync.bin)

It works on my 8.0 machine, at least.

**Comment by lukecyca** [comment] 2021-12-28 17:14
It works! Thanks so much.

**Comment by cy384** [comment] 2021-12-29 21:01
fixed (over in my mbedtls repo), it'll be working correctly in the next ssheven release

**Closed by cy384** 2021-12-29 21:01 UTC
Labels: bug
